ln -s /c/Users/dsilvio/Sites ~/Sites
ln -s /c/Users/dsilvio/Sites/dotfiles/.config ~/.config
ln -s /c/Users/dsilvio/Sites/dotfiles/.gitconfig ~/.gitconfig
ln -s /c/Users/dsilvio/Sites/dotfiles/.minttyrc ~/.minttyrc
ln -s /c/Users/dsilvio/Sites/dotfiles/.tmux ~/.tmux
ln -s /c/Users/dsilvio/Sites/dotfiles/.tmux.conf ~/.tmux.conf
ln -s /c/Users/dsilvio/Sites/dotfiles/.vim ~/.vim
ln -s /c/Users/dsilvio/Sites/dotfiles/.vimrc ~/.vimrc
ln -s /c/Users/dsilvio/Sites/dotfiles/.zshrc ~/.zshrc
ln -s ~/Sites /c/Users/dsilvio/Sites
